#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

SERVICE_NAME="seaweedfs"

start_service() {
    config_load ${SERVICE_NAME}
    config_foreach start_instance ${SERVICE_NAME}
}

start_instance() {
    local section="$1"
    config_get_bool enabled "$section" enabled 0
    [ "$enabled" -eq 1 ] || return 0

    config_get role "$section" role "server"
    config_get data_dir "$section" data_dir "/opt/seaweedfs"
    config_get extra_args "$section" extra_args ""
    config_get user "$section" user "root"

    mkdir -p "$data_dir"

    procd_open_instance
    procd_set_param command \
        /usr/bin/weed "$role" \
        -dir="$data_dir" \
        $extra_args

    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param user "$user"
    procd_set_param respawn
    procd_set_param file \
        /etc/config/${SERVICE_NAME}
    procd_close_instance
}

stop_service() {
    :
}

